{
    "name": "Sale Agent Commission",
    "summary": "Commission calculation and settlement for sales agents",
    "version": "19.0.1.0.0",
    "category": "Sales/Sales",
    "license": "AGPL-3",
    "author": "Ruben I Dominguez",
    "website": "https://github.com/Rbndominguez/sale_agent_commission",
    "depends": ["sale", "sale_margin", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "security/sale_commission_settlement_security.xml",
        "data/ir_sequence_data.xml",
        "views/res_users_views.xml",
        "views/sale_order_views.xml",
        "views/sale_commission_settlement_views.xml",
        "wizard/sale_commission_settlement_generate_views.xml",
    ],
    "installable": True,
    "application": False,
}